repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: autopep8-wrapper
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: flake8
        args: []
    -   id: pretty-format-json
        args: ["--autofix"]

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: master
    hooks:
    -   id: python-use-type-annotations
    -   id: python-no-eval

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest tests
        language: system
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true

    -   id: python-bandit-vulnerability-check
        name: bandit
        entry: bandit
        args: ['--ini', 'tox.ini', '-r', 'consoleme']
        language: system
        pass_filenames: false