exclude: "^docs/gitbook/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-case-conflict
      - id: check-yaml
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ["--exclude", "consoleme/models.py"]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/timothycrosley/isort
    rev: "5.6.4" # Use the revision sha / tag you want to point at
    hooks:
      - id: isort # Run `isort -rc <filepath>` to autofix
        pass_filenames: true
        args: ["--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
      - id: python-use-type-annotations
      - id: python-no-eval

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.24.0
    hooks:
      - id: eslint
        args:
          [
            "--fix",
            "--max-warnings",
            "0",
            "--resolve-plugins-relative-to",
            "./ui",
            "-c",
            "./ui/.eslintrc",
          ]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests
        language: system
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true

      - id: python-bandit-vulnerability-check
        name: bandit
        entry: bandit
        args: ["--ini", "tox.ini", "-r", "consoleme"]
        language: system
        pass_filenames: false
