extends:
  - example_config_base.yaml
  - example_secrets.yaml

development: true

url: http://127.0.0.1:8081

tornado:
  debug: true
  port: 8081
  xsrf: false

google:
  service_key_file: docker/test_google_secret.json

get_eligible_roles:
  from_config: true

dynamic_config:
  group_mapping:
    someuser@example.com:
      roles:
        - arn:aws:iam::123456789012:role/userrolename
    group1@example.com:
      roles:
        - arn:aws:iam::123456789012:role/rolename

duo:
  lambda_arn: arn:aws:lambda:{}:123456789012:function:duo_lambda

challenge:
  expiration: 600

celery_jobs:
  cloudtrail_errors:
    sleep_time: 0

logging:
  format: '%(asctime)s - %(levelname)s - %(name)s - [%(filename)s:%(lineno)s - %(funcName)s() ] - %(message)s'
  stdout_enabled: true
  level: debug
  elasticsearch:
    level: DEBUG
  file: ~/.consoleme/consoleme_tornado.log

aws:
  account_number: 123456789012
  region: us-east-1

ses:
  consoleme:
    sender: consoleme_test@fakedomain.com
    name: Consoleme
  accessui:
    sender: access_ui_test@fakedomain.com
    name: Access UI
