name: pre-commit

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Install dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo bash
          curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update
          sudo apt-get install \
            libssl-dev \
            libcurl4-openssl-dev \
            python3-dev \
            build-essential \
            libxml2-dev \
            libxmlsec1-dev \
            libxmlsec1-openssl \
            musl-dev \
            yarn \
            nodejs
          python3 -m pip install --upgrade pip
          pip install "setuptools==44.0.0"
          pip3 install \
            -r requirements.txt \
            -r requirements-test.txt \
            -r requirements-docs.txt
          pip3 install -e .
          yarn --cwd ui install
          yarn --cwd ui build:prod
          terraform -chdir=terraform/central-account/ init
          terraform -chdir=terraform/spoke-accounts/ init
          pre-commit install
      - name: Run pre-commit
        run: |
          pre-commit run -a
